services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    container_name: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - pr-assignment-tests:/var/lib/postgresql/

  pr-assignment:
    build:
      dockerfile: Dockerfile.tests
      context: ./
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      CONFIG_PATH: ./config/tests.yaml
    depends_on:
      db:
        condition: service_healthy
    container_name: pr-assignment

volumes:
  pr-assignment-tests: